apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-sequencer
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: function-sequencer
    input:
      apiVersion: template.fn.crossplane.io/v1beta1
      kind: Input
      sequence:
        - foo
        - bar
